### ISSUE TITLE
Suggestion: Add this splitter to the official list

### ISSUE THREAD

**Issue by jbzdarkid** [periwinkle9/cave-story-autosplitters#1]
Livesplit comes with a list of autosplitters: https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit.AutoSplitters.xml
If an autosplitter is in this list, then setting your game (in livesplit) to, e.g., cave story will cause the associated .asl to download, and to be available directly on the splits as an autosplitter.

This is a bit easier for users, since they don't have to add a manual component, and it also saves the autosplitter settings into the .lss file (so different split files can have different splitter settings).
Furthermore, it serves as an update mechanism. Not that this game is seeing a lot of updates, of course, but new categories or tricks can prompt new split points, and this system means you can distribute updates to all users, automatically.

**Comment by periwinkle9** [comment]
It has been done.
